// src/components/Header.vue
<template>
  <header class="z-10 px-2 text-white h-16 bg-blue-600 fixed flex w-full items-center shadow-md border-b border-blue-700">
    <div class="w-full flex items-baseline">
      <template v-if="!recipe">
        <div class="flex-grow flex">
          <div class="flex-grow self-center">{{ t('Ingredient converter') }}</div>
          <div class="flex-shrink">
            <template v-if="userLoading">
              <Icon icon="fal fa-sync fa-spin mr-4" size="1.2rem" />
            </template>
            <template v-else>
              <Button class="shadow-none" v-if="user" @click="logout()">
                <Icon :icon="didSynced ? 'fal fa-sync fa-spin' : 'fal fa-sign-out'" size="1.2rem" />
              </Button>
              <Button class="shadow-none" v-else @click="loginWithRedirect()">
                <Icon icon="fal fa-cloud-upload" size="1.2rem" />
              </Button>
            </template>
          </div>
        </div>
      </template>
      <template v-else>
        <div class="flex-grow">
          <Button class="shadow-none" @click="home">
            <Icon icon="fal fa-arrow-alt-left" size="1.2rem" />
          </Button>
        </div>
      </template>

      <template v-if="recipe">
        <SInput
          class="w-20"
          :placeholder="t('Original amount')"
          type="number"
          @enter="focusNext"
          @update="onchange"
          v-model="recipe.original"
        />
        <Icon class="mx-1" style="top: 3px;" size="1.6rem" icon="fal fa-play-circle" />
        <SInput
          class="w-20"
          :placeholder="t('Target amount')"
          type="number"
          id="input-desired"
          ref="elDesire"
          @enter="blurInput"
          @update="onchange"
          v-model="recipe.desired"
        />
      </template>
    </div>
  </header>
</template>

<script lang="ts" setup>
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { loginWithRedirect, logout } from 'thin-backend'
import { recipes, didSynced as _didSynced } from '~src/store/index'
import { t } from '~src/i18n'
import { user, userLoading } from '~src/services/auth'
import SInput from '~components/Input.vue'
import Icon from './Icon.vue'
import Button from './Button.vue'

const didSynced = computed(() => _didSynced.value)
const route = useRoute()
const router = useRouter()

const recipeId = computed(() => {
  if (route.path.startsWith('/recipe/')) {
    const id = route.params.id
    return typeof id === 'string' ? +id : -1
  }
  return -1
})

const recipe = computed<any>({
  get() {
    return recipeId.value !== -1 ? recipes.value[recipeId.value] : null
  },
  set(v) {
    if (recipeId.value !== -1) {
      const copy = [...recipes.value]
      copy[recipeId.value] = v
      recipes.value = copy
    }
  },
})

function onchange() {
  if (recipeId.value !== -1) {
    const copy = [...recipes.value]
    copy[recipeId.value] = recipe.value
    recipes.value = copy
  }
}

const elDesire = ref<any>(null)
function focusNext() {
  elDesire.value?.focus()
}
function blurInput(e: any) {
  e.detail?.el?.blur?.()
}
function home() {
  router.push('/')
}
</script>

// src/components/Header.svelte
<header
  class="z-10 px-2 text-white h-16 bg-blue-600 fixed flex w-full items-center shadow-md border-b border-blue-700">
  <div class="w-full flex items-baseline">
    {#if !recipe}
      <div class="flex-grow flex">
        <div class="flex-grow self-center">{$_('材料コンバーター')}</div>
        <div class="flex-shrink">
          {#await userPromise}
            <Icon icon="fal fa-sync fa-spin mr-4" size="1.2rem" />
          {:then user}
            {#if !!user}
              <Button class="shadow-none" on:click={() => logout()}>
                {#if $didSynced}
                  <Icon icon="fal fa-sync fa-spin" size="1.2rem" />
                {:else}
                  <Icon icon="fal fa-sign-out" size="1.2rem" />
                {/if}
              </Button>
            {:else}
              <Button class="shadow-none" on:click={() => loginWithRedirect()}>
                <Icon icon="fal fa-cloud-upload" size="1.2rem" />
              </Button>
            {/if}
          {/await}
        </div>
      </div>
    {:else}
      <div class="flex-grow">
        <Button class="shadow-none" on:click={() => home()}>
          <Icon icon="fal fa-arrow-alt-left" size="1.2rem" />
        </Button>
      </div>
    {/if}

    {#if !!recipe}
      <SInput
        class="w-20"
        placeholder={$_('必要量')}
        type="number"
        on:enter={focusNext}
        on:input={onchange}
        bind:value={recipe.original} />
      <Icon
        class="mx-1"
        style="top: 3px;"
        size="1.6rem"
        icon="fal fa-play-circle" />
      <SInput
        class="w-20"
        placeholder={$_('最低量')}
        type="number"
        id="input-desired"
        bind:elInput={elDesire}
        on:enter={blur}
        on:input={onchange}
        bind:value={recipe.desired} />
    {/if}
  </div>
</header>

<script>
  import { _ } from 'svelte-i18n'
  import { loginWithRedirect, logout } from 'thin-backend'
  import { userPromise } from '~src'
  import { recipes, route } from '~src/store'
  import { push } from 'svelte-spa-router'

  let elDesire
  let recipe

  let recipeId = -1
  route.subscribe((r) => {
    recipeId = r.location?.startsWith('/recipe/') ? r.location.slice(8) : -1
  })

  $: recipe = recipeId !== -1 ? $recipes[recipeId] : null

  import SInput from '~components/Input.svelte'
  import { didSynced } from '~src/store/index.js'
  import Icon from './Icon.svelte'
  import Button from './Button.svelte'

  userPromise.then(console.log)

  function onchange() {
    $recipes[recipeId] = recipe
    recipes.set($recipes)
  }

  function focusNext() {
    elDesire.focus()
  }

  function blur(ev) {
    ev.detail.el.blur()
  }

  function home() {
    push('/')
  }

</script>
