// src/components/Recipe.svelte
{#if recipe}
  <div class="flex items-center">
    <div
      class="title flex-1 whitespace-no-wrap overflow-hidden text-xs px-1 font-bold text-gray-700">
      {recipe?.name}
    </div>

    {#if !recipe.checklist}
      <Button on:click={switchEdit} class="mr-1" color="green">
        {#if recipe.edit}
          <Icon icon="fal fa-eye" class="mr-1" size="0.8rem" />
          表示モード
        {:else}
          <Icon icon="fal fa-pen" class="mr-1" size="0.8rem" />
          編集モード
        {/if}
      </Button>
    {:else}
      <Button on:click={clearCheck} class="mr-1" color="gray">
        <Icon icon="fal fa-broom" class="mr-1" size="0.8rem" />
        クリア
      </Button>
    {/if}
    {#if !recipe.edit}
      <Button on:click={switchCheck} color="gray">
        {#if recipe.checklist}
          <Icon icon="fal fa-eye" class="mr-1" size="0.8rem" />
          表示モード
        {:else}
          <Icon icon="fal fa-shopping-cart" class="mr-1" size="0.8rem" />
          チェックリスト
        {/if}
      </Button>
    {/if}
  </div>
  <div class="flex flex-col">
    <div class="mb-3 mt-2">
      {#each recipe.ingredients as item, index}
        <div class="grid grid-cols-12 mb-2 gap-1" value={recipe.ingredients}>
          {#if recipe.edit}
            <SInput
              placeholder="材料"
              class="col-span-6"
              inputClass="input-field"
              id="input-name-{index}"
              on:enter={focusNext}
              bind:value={item.name} />
            <SInput
              placeholder="分量"
              class="col-span-3"
              inputClass="input-field"
              type="number"
              id="input-amount-{index}"
              on:enter={focusNext}
              bind:value={item.amount} />
            <AmountTypeModal
              bind:this={item._inputAmountType}
              class="col-span-3"
              bind:value={item.amountType} />
          {/if}
          <div
            class="col-span-12 px-3 pb-3 pt-5 rounded-lg relative bg-gray-900 text-2xl text-white">
            <div class="grid grid-cols-12">
              <div class="col-span-10">
                <div class="absolute left-0 top-0 text-xs ml-3 mt-1">
                  必要な量
                </div>
                <span
                  class="text-gray-300 font-bold"
                  on:click={() => clickName(index)}>{item.name || '-'}</span>
                {#if ['大さじ', '小さじ'].includes(item.amountType)}
                  <span
                    class="text-red-300"
                    on:click={() => clickAmountType(item._inputAmountType)}
                    style="font-size: 1.2rem;">{item.amountType}</span>
                {/if}
                <span
                  class="font-bold"
                  on:click={() => clickAmount(index)}>{amount(item, item.amountType)}</span>
                {#if !['大さじ', '小さじ'].includes(item.amountType)}
                  <span
                    class="text-red-300"
                    on:click={() => clickAmountType(item._inputAmountType)}
                    style="font-size: 1.2rem;">{item.amountType}</span>
                {/if}
              </div>
              <div class="col-span-2 relative text-right">
                {#if recipe.checklist}
                  <Checkbox
                    class="absolute right-0 top-0 -mt-1"
                    bind:value={item.checked}
                    on:input={saveChange} />
                {:else if !recipe.edit}
                  <div
                    class="text-xs whitespace-no-wrap absolute top-0 -mt-4 right-0 text-gray-500">
                    <span class="text-gray-700">オリジナル </span>
                    {item.amount || '0'}
                  </div>
                  <i
                    on:click={() => doOriginal(index)}
                    class="cursor-pointer fal fa-ruler p-2 top-0 -mt-1 {recipe.edit ? 'mr-10' : ''} absolute right-0 text-gray-600" />
                {/if}
                {#if recipe.edit}
                  <i
                    on:click={() => moveDown(index)}
                    class="text-sm cursor-pointer fal fa-arrow-down p-2 top-0 mr-24 absolute right-0 text-gray-600" />
                  <i
                    on:click={() => moveUp(index)}
                    class="text-sm cursor-pointer fal fa-arrow-up p-2 top-0 mr-16 absolute right-0 text-gray-600" />
                  <i
                    on:click={() => deleteIngredient(index)}
                    class="cursor-pointer fal fa-minus-circle p-2 top-0 -mt-1 absolute right-0 text-gray-600" />
                {/if}
              </div>
            </div>
          </div>
        </div>
      {/each}
    </div>
    <div class="mb-4 mt-2 text-right">
      {#if recipe.edit}
        <Button on:click={addIngredient} color="green">
          <Icon icon="fal fa-plus" class="mr-1" size="1.2rem" />
          追加
        </Button>
      {/if}
    </div>
    <div class="flex mt-4">
      {#if recipe.edit}
        <SInput
          placeholder="レシピのURL"
          class="flex-grow"
          on:input={() => ($recipes[$openedRecipe].url = recipe.url)}
          bind:value={recipe.url} />
      {/if}
      {#if recipe.url}
        <a href={recipe.url} class="ml-2" target="_blank" rel="noreferrer">
          <Button class="whitespace-no-wrap">リンクを開く</Button></a>
      {/if}
    </div>
    <div>
      {#if recipe.edit}
        <textarea
          placeholder="ノート"
          style="height: 200px;"
          class="mt-2 w-full focus:ring-indigo-500 text-black p-2 focus:border-indigo-500 shadow-sm sm:text-sm border-gray-300 rounded-md"
          bind:value={recipe.note}
          on:input={() => ($recipes[$openedRecipe].note = recipe.note)} />
      {:else if recipe.note}
        <p class="text-sm mt-3 px-2"><b>ノート:</b></p>
        <p class="text-sm px-2">{recipe.note}</p>
      {/if}
    </div>
  </div>
{/if}

<script>
  import { openedRecipe } from '~src/store'
  import { recipes } from '~src/store'

  if (!$recipes || $recipes.length === 0) {
    openedRecipe.set(-1)
  }

  let ratio
  $: ratio = recipe.original / recipe.desired

  let recipe
  $: recipe = $openedRecipe !== -1 ? $recipes[$openedRecipe] : null

  import Button from './Button.svelte'
  import SInput from './Input.svelte'
  import Icon from './Icon.svelte'
  import { newIngredient } from '~plugins/helper'
  import Checkbox from './Checkbox.svelte'
  import AmountTypeModal from './AmountTypeModal.svelte'

  function clickName(index) {
    document.getElementById('input-name-' + index)?.focus()
  }

  function clickAmount(index) {
    document.getElementById('input-amount-' + index)?.focus()
  }

  function clickAmountType(item) {
    item?.focus()
  }

  function addIngredient() {
    $recipes[$openedRecipe].ingredients.push(newIngredient())
    recipes.set($recipes)
    setTimeout(() => {
      let items = [...document.getElementsByClassName('input-field')]
      items[items.length - 2].focus()
    }, 0)
  }

  function switchEdit() {
    $recipes[$openedRecipe].edit = !$recipes[$openedRecipe].edit
    $recipes[$openedRecipe].checklist = false
    recipes.set($recipes)
  }

  function switchCheck() {
    $recipes[$openedRecipe].checklist = !$recipes[$openedRecipe].checklist
    $recipes[$openedRecipe].edit = false
    recipes.set($recipes)
  }

  function clearCheck() {
    $recipes[$openedRecipe].ingredients.forEach((i) => {
      i.checked = false
    })

    $recipes[$openedRecipe].edit = false
    recipes.set($recipes)
  }

  function saveChange() {
    setTimeout(() => {
      recipes.set($recipes)
    }, 0)
  }

  function focusNext() {
    const current = document.activeElement
    let items = [...document.getElementsByClassName('input-field')]
    const currentIndex = items.indexOf(current)
    let newIndex

    if (currentIndex === -1) {
      newIndex = 0
    } else {
      newIndex = currentIndex + 1
    }
    current.blur()
    if (newIndex >= items.length) {
      addIngredient()
      setTimeout(() => {
        items = [...document.getElementsByClassName('input-field')]
        items[items.length - 2].focus()
      }, 0)
    }
    if (items[newIndex]) {
      items[newIndex].focus()
    }
  }

  function amount(item, amountType) {
    let useQuarter
    const rat = ratio || 1

    switch (amountType) {
      case '少々':
        return Math.ceil(item.amount / rat).toFixed(0)
      case 'g':
      case '㏄':
        if (item.amount > 1) {
          return Math.round(item.amount / rat)
        }
        break
      case '大さじ':
      case '小さじ':
      case '個':
        useQuarter = true
        break
      default:
        useQuarter = false
    }
    if (useQuarter) {
      let amount = (Math.round((item.amount / rat) * 4) / 4).toFixed(2)
      if (amount.includes('.')) {
        let [number, decimal] = amount.split('.')

        if (decimal) {
          number = +number === 0 ? '' : number
        }
        switch (decimal) {
          case '25':
            amount = number + ' ' + '¼'
            break
          case '50':
            amount = number + ' ' + '½'
            break
          case '75':
            amount = number + ' ' + '¾'
            break
          default:
            amount = number
        }
      }
      return !amount ? 0 : amount
    }

    return parseFloat((item.amount / rat).toFixed(2)) || '0'
  }

  function doOriginal(index) {
    recipes.update((r) => {
      r[$openedRecipe].original = r[$openedRecipe].ingredients[index].amount
      r[$openedRecipe].desired = r[$openedRecipe].ingredients[index].amount
      return r
    })
    document.getElementById('input-desired')?.focus()
    setTimeout(() => {
      document.getElementById('input-desired')?.select()
    }, 0)
  }

  function array_move(array, sourceIndex, destinationIndex) {
    const smallerIndex = Math.min(sourceIndex, destinationIndex)
    const largerIndex = Math.max(sourceIndex, destinationIndex)

    return [
      ...array.slice(0, smallerIndex),
      ...(sourceIndex < destinationIndex
        ? array.slice(smallerIndex + 1, largerIndex + 1)
        : []),
      array[sourceIndex],
      ...(sourceIndex > destinationIndex
        ? array.slice(smallerIndex, largerIndex)
        : []),
      ...array.slice(largerIndex + 1),
    ]
  }

  function moveUp(index) {
    recipes.update((r) => {
      const clamp = Math.max(0, index - 1)
      r[$openedRecipe].ingredients = array_move(
        r[$openedRecipe].ingredients,
        index,
        clamp
      )
      return r
    })
  }

  function moveDown(index) {
    recipes.update((r) => {
      const clamp = Math.min(r[$openedRecipe].ingredients.length - 1, index + 1)
      r[$openedRecipe].ingredients = array_move(
        r[$openedRecipe].ingredients,
        index,
        clamp
      )
      return r
    })
  }

  function deleteIngredient(index) {
    recipes.update((r) => {
      r[$openedRecipe].ingredients = r[$openedRecipe].ingredients.filter(
        (a, i) => i !== index
      )
      return r
    })
  }
</script>

<style>
  .title {
    text-overflow: ellipsis;
    white-space: nowrap;
  }
</style>

// src/components/Recipe.vue
<template>
  <div v-if="recipe" class='flex-grow flex flex-col'>
    <div class="flex items-center my-1">
      <div class="title flex-1 whitespace-nowrap overflow-hidden text-xs px-1 font-bold text-gray-700">
        {{ recipe?.name }}
      </div>

      <template v-if="!recipe.checklist">
        <Button @click="switchEdit" class="mr-1" color="green">
          <template v-if="recipe.edit">
            <Icon icon="fal fa-eye" class="mr-1" size="0.8rem" />
            {{ t('View mode') }}
          </template>
          <template v-else>
            <Icon icon="fal fa-pen" class="mr-1" size="0.8rem" />
            {{ t('Edit mode') }}
          </template>
        </Button>
      </template>
      <template v-else>
        <Button @click="clearCheck" class="mr-1" color="gray">
          <Icon icon="fal fa-broom" class="mr-1" size="0.8rem" />
          {{ t('Clear') }}
        </Button>
      </template>
      <template v-if="!recipe.edit">
        <Button @click="switchCheck" color="gray">
          <template v-if="recipe.checklist">
            <Icon icon="fal fa-eye" class="mr-1" size="0.8rem" />
            {{ t('View mode') }}
          </template>
          <template v-else>
            <Icon icon="fal fa-shopping-cart" class="mr-1" size="0.8rem" />
            {{ t('Checklist') }}
          </template>
        </Button>
      </template>
    </div>
    <div class="flex flex-col flex-grow">
      <div class="mb-3 mt-2">
        <div class="grid grid-cols-12 mb-3 gap-1" v-for="(item, index) in recipe.ingredients" :key="index">
          <template v-if="recipe.edit">
            <SInput
              :placeholder="t('Ingredient')"
              class="col-span-6"
              inputClass="input-field"
              :id="'input-name-' + index"
              @enter="() => focusNext(index)"
              @update="saveChange"
              v-model="item.name"
            />
            <SInput
              :placeholder="t('Amount')"
              class="col-span-3"
              inputClass="input-field"
              type="number"
              :id="'input-amount-' + index"
              @update="saveChange"
              @enter="() => focusNext(index)"
              v-model="item.amount"
            />
            <AmountTypeModal
              :ref="(el:any) => (amountRefs[index] = el)"
              class="col-span-3"
              @update="saveChange"
              v-model="item.amountType"
            />
          </template>
          <div class="col-span-12 px-3 pb-3 pt-5 rounded-lg relative bg-gray-900 text-2xl text-white">
            <div class="grid grid-cols-12">
              <div class="col-span-10">
                <div class="absolute left-0 text-gray-600 top-0 text-xs ml-3 mt-1">
                  {{ t('Needed amount') }}
                </div>
                  <span class="text-gray-300 font-bold mr-2" @click="() => clickName(index)">{{ item.name || '-' }}</span>
                  <template v-if="unitBefore(item.amountType as any)">
                    <span
                      class="text-red-300"
                      @click="() => clickAmountType(index)"
                      style="font-size: 1.2rem;"
                      >{{ unitLabel(item.amountType as any) }}</span>
                    <span class="font-bold" @click="() => clickAmount(index)">{{ amount(item) }}</span>
                  </template>
                  <template v-else>
                    <span class="font-bold" @click="() => clickAmount(index)">{{ amount(item) }}</span>
                    <span
                      class="text-red-300"
                      @click="() => clickAmountType(index)"
                      style="font-size: 1.2rem;"
                      >{{ unitLabel(item.amountType as any) }}</span>
                  </template>
              </div>
              <div class="col-span-2 relative text-right">
                <template v-if="recipe.checklist">
                  <Checkbox class="absolute right-0 top-0 -mt-1" v-model="item.checked" @input="saveChange" />
                </template>
                <template v-else-if="!recipe.edit">
                  <div class="text-xs whitespace-nowrap absolute top-0 -mt-4 right-0 text-gray-500">
                    <span class="text-gray-600">{{ t('Original') }} </span>
                    {{ item.amount || '0' }}
                  </div>
                  <i
                    @click="() => doOriginal(index)"
                    class="cursor-pointer fal fa-ruler p-2 top-0 -mt-1 absolute right-0 text-gray-600"
                  />
                </template>
                <template v-if="recipe.edit">
                  <i @click="() => moveDown(index)" class="text-sm cursor-pointer fal fa-arrow-down p-2 top-0 mr-24 absolute right-0 text-gray-600" />
                  <i @click="() => moveUp(index)" class="text-sm cursor-pointer fal fa-arrow-up p-2 top-0 mr-16 absolute right-0 text-gray-600" />
                  <i @click="() => deleteIngredient(index)" class="cursor-pointer fal fa-minus-circle p-2 top-0 -mt-1 absolute right-0 text-gray-600" />
                </template>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="mb-4 mt-2 text-right">
        <template v-if="recipe.edit">
          <Button @click="addIngredient" color="green">
            <Icon icon="fal fa-plus" class="mr-1" size="1.2rem" />
            {{ t('Add') }}
          </Button>
        </template>
      </div>
      <div class="flex mt-4">
        <template v-if="recipe.edit">
          <SInput :placeholder="t('Recipe URL')" class="flex-grow" @update="saveChange" v-model="recipe.url" />
        </template>
        <template v-if="recipe.url">
          <a :href="recipe.url" class="ml-2" target="_blank" rel="noreferrer">
            <Button class="whitespace-nowrap">
              {{ t('Open recipe web page') }}
              <i class="fal fa-external-link ml-2" />
            </Button>
          </a>
        </template>
      </div>
      <div>
        <template v-if="recipe.edit">
          <textarea
            :placeholder="t('Note')"
            style="height: 200px"
            class="mt-2 w-full focus:ring-indigo-500 text-black p-2 focus:border-indigo-500 shadow-sm sm:text-sm border-gray-300 rounded-md"
            @input="saveChange"
            v-model="recipe.note"
          />
        </template>
        <template v-else-if="recipe.note">
          <p class="text-sm mt-3 px-2"><b>{{ t('Note') }}:</b></p>
          <div class="markdown text-sm px-2" v-html="markedRender"></div>
        </template>
      </div>
    </div>
    <Footer />
  </div>
</template>

<script lang="ts" setup>
import { computed, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import * as marked from 'marked'
import Footer from '~components/Footer.vue'
import { recipes as _recipes } from '~src/store/index'
import Button from './Button.vue'
import SInput from './Input.vue'
import Icon from './Icon.vue'
import Checkbox from './Checkbox.vue'
import AmountTypeModal from './AmountTypeModal.vue'
import { t } from '~src/i18n'
import { normalizeAmountType } from '~src/services/units'

const route = useRoute()
const router = useRouter()

const recipeId = computed(() => {
  return +(route.params.id as any)
})

const recipe = computed<any>({
  get() {
    return _recipes.value?.[recipeId.value]
  },
  set(v) {
    const copy = [..._recipes.value]
    copy[recipeId.value] = v
    _recipes.value = copy
  },
})

if (!_recipes.value || _recipes.value.length === 0) {
  router.push('/')
}

// Ensure view mode when opening a recipe: if currently in edit mode, switch to view
watch(
  () => recipeId.value,
  (id) => {
    const list = _recipes.value
    if (!Array.isArray(list) || id == null) return
    const current = list[id]
    if (current && current.edit) {
      const copy = [...list]
      copy[id] = { ...copy[id], edit: false }
      _recipes.value = copy
    }
  },
  { immediate: true }
)

const markedRender = computed(() => marked.parse(recipe.value?.note || ''))
const ratio = computed(() => (recipe.value ? recipe.value.original / recipe.value.desired : 1))

function norm(type: string): string {
  return normalizeAmountType(type)
}

  function amount(item: any): string | number {
    const rat = ratio.value || 1
    const raw = parseFloat((item?.amount ?? 0) as any)
    if (!raw) return '0'
    const type = norm(item?.amountType)

    // Pinch: round up to an integer count
    if (type === 'pinch') {
      return Math.ceil(raw / rat).toFixed(0)
    }

    // Grams/ml: show integer when > 1, otherwise fall through to precise display
    if (type === 'g' || type === 'ml') {
      if (raw > 1) {
        return Math.round(raw / rat)
      }
      // else fall through to generic handling below
    }

    // Units that prefer quarters (¼ ½ ¾)
    const quarterUnits = ['tbl', 'tea', 'p']
    const useQuarter = quarterUnits.includes(type)
    if (useQuarter) {
      let amt = ((Math.round((raw / rat) * 4) / 4).toFixed(2))
      if (amt.includes('.')) {
        let [num, dec] = amt.split('.')
        if (dec) {
          num = +num === 0 ? '' : num
        }
        switch (dec) {
          case '25':
            amt = (num ? num + ' ' : '') + '¼'
            break
          case '50':
            amt = (num ? num + ' ' : '') + '½'
            break
          case '75':
            amt = (num ? num + ' ' : '') + '¾'
            break
          default:
            amt = num
        }
      }
      return amt ? amt : 0
    }

    // Generic: show up to 2 decimals, trim trailing zeros
    const precise = parseFloat(((raw / rat).toFixed(2)))
    return (isNaN(precise) ? 0 : precise)
  }

  function unitBefore(type: string): boolean {
    return ['tbl', 'tea'].includes(norm(type))
  }

  function unitLabel(type: string): string {
    return t('full_' + norm(type))
  }

const amountRefs = ref<any[]>([])
function clickName(index: number) {
  document.getElementById('input-name-' + index)?.focus()
}
function clickAmount(index: number) {
  document.getElementById('input-amount-' + index)?.focus()
}
function clickAmountType(index: number) {
  amountRefs.value?.[index]?.focus?.()
}
function focusNext(index: number) {
  const active = document.activeElement as HTMLElement | null
  if (active?.id === 'input-name-' + index) {
    document.getElementById('input-amount-' + index)?.focus()
    return
  }
  if (active?.id === 'input-amount-' + index) {
    amountRefs.value?.[index]?.focus?.()
    return
  }
  const nextName = document.getElementById('input-name-' + (index + 1))
  nextName?.focus()
}
function addIngredient() {
  const copy = [..._recipes.value]
  copy[recipeId.value].ingredients.push({ name: '', amount: '', amountType: 'g', note: '' })
  _recipes.value = copy
  setTimeout(() => {
    const items = [...document.getElementsByClassName('input-field')] as HTMLElement[]
    items[items.length - 2]?.focus()
  }, 0)
}
function switchEdit() {
  const copy = [..._recipes.value]
  copy[recipeId.value].edit = !copy[recipeId.value].edit
  copy[recipeId.value].checklist = false
  _recipes.value = copy
}
function switchCheck() {
  const copy = [..._recipes.value]
  copy[recipeId.value].checklist = !copy[recipeId.value].checklist
  copy[recipeId.value].edit = false
  _recipes.value = copy
}
function clearCheck() {
  const copy = [..._recipes.value]
  copy[recipeId.value].ingredients.forEach((i: any) => (i.checked = false))
  _recipes.value = copy
}
function doOriginal(index: number) {
  const item = recipe.value?.ingredients?.[index]
  if (!item) return
  const amount = parseFloat(item.amount || '0')
  if (!amount) return
  const copy = [..._recipes.value]
  copy[recipeId.value].original = amount
  copy[recipeId.value].desired = amount
  _recipes.value = copy
  setTimeout(() => {
    document.getElementById('input-desired')?.focus()
  }, 0)
}
function array_move<T>(array: T[], sourceIndex: number, destinationIndex: number): T[] {
  const smallerIndex = Math.min(sourceIndex, destinationIndex)
  const largerIndex = Math.max(sourceIndex, destinationIndex)
  return [
    ...array.slice(0, smallerIndex),
    ...(sourceIndex < destinationIndex ? array.slice(smallerIndex + 1, largerIndex + 1) : []),
    array[sourceIndex],
    ...(sourceIndex > destinationIndex ? array.slice(smallerIndex, largerIndex) : []),
    ...array.slice(largerIndex + 1),
  ]
}
function moveUp(index: number) {
  const copy = [..._recipes.value]
  const clamp = Math.max(0, index - 1)
  copy[recipeId.value].ingredients = array_move(copy[recipeId.value].ingredients, index, clamp)
  _recipes.value = copy
}
function moveDown(index: number) {
  const copy = [..._recipes.value]
  const clamp = Math.min(copy[recipeId.value].ingredients.length - 1, index + 1)
  copy[recipeId.value].ingredients = array_move(copy[recipeId.value].ingredients, index, clamp)
  _recipes.value = copy
}
function deleteIngredient(index: number) {
  const copy = [..._recipes.value]
  copy[recipeId.value].ingredients = copy[recipeId.value].ingredients.filter((_: any, i: number) => i !== index)
  _recipes.value = copy
}
function saveChange() {
  // recipes ref is reactive; assigning above triggers persistence via external calls
}
</script>

<style scoped>
.title {
  text-overflow: ellipsis;
  white-space: nowrap;
}

</style>
